### ISSUE TITLE
Feedback Received Collated and distributed amongst team mates

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/Pythoshop#101]
Let's consolidate the feedback from all reviewers here and we can then move the exact to-dos to the milestone 4 fixes issues

**Comment by salva-u** [comment]
- [x]  Update the docs to say Before vs After for resize_image @salva-u 
- [x]  transform_image does not have an example section @ella-irene 
- [x]  add the missing badges: Continuous integration and test coverage, repostatus badge, Python versions supported badge, current package version badge) @ella-irene 
- [x]  resize_image: consistent doc string @salva-u 
- [x]  conda install poetry in readme @ella-irene 
- [x]  add verbose flag to transform_image, adjust_brightness, apply_filter 
- [x]  have at least 80% coverage of tests - @salva-u @jlee2843 @ella-irene @Rachel0619 
- [x]  try to fix the readthedocs menu toggle issue @jlee2843 
- [x]  Reduce the number of images in the test @Rachel0619 
- [x]  FileNotfound error fixed already 
- [x] adjust_brightness make sure the docs have the example here 
- [x] double check unused imports @salva-u @jlee2843 @Rachel0619 @ella-irene

**Comment by Rachel0619** [comment]
The link for peer review:
https://github.com/UBC-MDS/software-review-2024/issues/7

**Comment by Rachel0619** [comment]
Summary of feedbacks from the grader:
1. Function documentation & code style
- for the adjust_brightness function docs, examples should be in the docstring, not a comment at the bottom
- for the `apply_filter` function, the sentence on line 10 which generally describes the function is not complete. Also, it says to choose from a list of filters, but there is no list in the function documentation

2. Function design
The function design looks great overall except that the current function designs for (adjust_brightness, apply_filter, resize_image, and transform_image) all involve reading an image from a path, performing adjustments, and then saving the modified image back to a path. Thus, they are performing three tasks at a time (more than one task). We have decided that 3 marks would need to be deducted for each function, hence, a total of 12 marks. We suggest that you manipulate an image object instead of retrieving and saving it to a file path.

3. Test design
For each of test_apply_filter, test_resize_image, and test_transform_image, you only performed one test. For example, in test_apply_filter, you only test for "red" but in your original apply_filter function, you have five methods(red, sepia, blue, green, and grey). We decided that 3 marks will have to be deducted for each question.

4. Test code accuracy, coverage & automation
- The test opens up images which can cause downstream issues on GitHubactions since no one will be there to close them.
- Code branch coverage is only between 61-80%
src\pythoshop\adjust_brightness.py: 78%,
src\pythoshop\transform_image.py: 70%,
src\pythoshop\apply_filter.py: 67%,
src\pythoshop\transform_image.py: 70%
- All your test suits will need documentation/comments and they are currently missing.

**Comment by salva-u** [comment]
All Feedback from Milestone 2 has been implemented except the checks on code coverage may be pending

**Comment by salva-u** [comment]
done
