### ISSUE TITLE
The license choice

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/Pythoshop#92]
At this moment, we may want to examine the license for our project and consider whether this is the choice we want to make, or whether we want to change the license

**Comment by ella-irene** [comment]
What are our options? I am most familiar with MIT and the creative commons licenses.

**Comment by jlee2843** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository These are the lists from the GitHub website!

**Comment by salva-u** [comment]
https://choosealicense.com/ let's look at this

**Comment by salva-u** [comment]
What do we think about this license ?
https://choosealicense.com/licenses/gpl-3.0/

**Comment by salva-u** [comment]
So as per our discussions, I think the best option is we go with GNU General Public License (GPL) v3: 
1) Strong Copyleft Meaning modifications of our software must also be distributed under the same license.: This helps ensure that improvements and modifications to your codebase are also open source, contributing to the broader open source community.
2) Community Collaboration: Contributors are more likely to share their enhancements and modifications because the license requires them to contribute back to the open source community.
3) Legal Protections: The GPL provides legal protection for users and developers by ensuring that they have the freedom to use, modify, and share the software.

**Comment by ella-irene** [comment]
I think that sounds good! I like the freedom of this license, especially how it encourages contributors to add enhancements and modifications.

**Comment by Rachel0619** [comment]
I think Apache License is another good choice here. Let's also discuss about this one. 

About Apache: The Apache License 2.0 is a permissive license that allows users to use, modify, distribute, and sublicense your code without the requirement that derivative works be distributed under the same license.

One good thing about this license is that the Apache License 2.0 includes an explicit patent grant clause, providing users with protection against patent claims related to the licensed software.

Nevertheless, Unlike strong copyleft licenses such as the GPL, the Apache License 2.0 does not require users who distribute the software to also distribute their modifications as open source.

We can vote after group discussion based on the above info

**Comment by jlee2843** [comment]
Both Apache License and GNU General Public License seem to be good options. I personally am leaning towards using GNU General Public, since our package is still in the development stage and there are a lot of potential updates that can be made to be more functional, but I'm not sure if we will need that explicit parent grant clause which is offered by Apache.

**Comment by salva-u** [comment]
Since everyone is leaning towards GNU, we will go with that
